import { Package } from '@/features/academy/types/models';

export const packagesContent = {
  hero: {
    badge: "Flexible learning. Real skills. Real income.",
    headline: "Choose the Program That Matches Your Goals",
    description: "Practical training. Real projects. Lifetime access. Career support.",
  },
  packages: [
    {
      id: "digital-marketing",
      title: "Digital Marketing Course",
      priceValue: 10000,
      offlinePriceValue: 15000,
      period: "One-time",
      duration: "2-3 Weeks",
      level: "Beginner Friendly",
      badge: "Starter",
      support: "Community Access",
      supportIcon: "Users",
      icon: 'Megaphone',
      popular: false,
      accent: "#A03BB8", // primary
      description: "Master the essentials of digital growth and social media management.",
      features: [
        "Introduction to Digital Marketing in Details.",
        "Market Analysis for Business & Creators.",
        "Professional Page Creations & Customizations.",
        "Canva Design (Graphic Design).",
        "SEO Trainings (Search Engine Optimizations).",
        "AI Tools for Marketing.",
        "Content Creation for Advertisement.",
        "A/B Testing & Campaign Optimizations.",
        "Social Media & Content Marketing.",
        "Boost Trainings (Meta Ads).",
        "Data Analytics & Optimizations.",
        "Referral Earning (Reward).",
        "Professional Guidance & Mentorship.",
        "Support & Community Access.",

      ],
    },
    {
      id: "business-package",
      title: "Business Package",
      priceValue: 21000,
      offlinePriceValue: 26000,
      period: "One-time",
      duration: "4-5 Weeks",
      level: "Beginner to Intermediate",
      badge: "Business Growth",
      support: "Lifetime Community Access",
      supportIcon: "Users",
      icon: 'Briefcase',
      popular: true,
      accent: "#3B82F6", // blue
      description: "The complete monetization stack for creators and digital freelancers.",
      features: [
        "Earning from Facebook page training in Details.",
        "Professional FB Page Creations & Customizations.",
        "Detailed setup & video creations training in Details.",
        "SEO Trainings (Search Engine Optimizations) in Details.",
        "Earning from Google Adsense training in Details.",
        "YouTube channel create & customizations in Details.",
        "YouTube channel training in Details.",
        "Domain & Hosting detailed knowledge & its benefits.",
        "Earning from National & International advertisement network in Details.",
        "Canva Design Trainings (Graphic Design) in Details.",
        "Online Business Training in Details.",
        "Boost Trainings (Meta Ads) in Details.",
        "Digital Marketing Training in Details.",
        "Installations of Video Editing Software.",
        "Basic Video Editing Trainings.",
        "Referral Earnings.",
        "Professional Guidance & Mentorship.",
        "Support & Community Access.",
      ],
    },
    {
      id: "professional-package",
      title: "Professional Package",
      priceValue: 45000,
      offlinePriceValue: 55000,
      period: "One-time",
      duration: "6-7 Weeks",
      level: "Intermediate to Advanced",
      badge: "Agency Mastery",
      support: "Priority Support",
      supportIcon: "Headphones",
      icon: 'Code2',
      popular: false,
      accent: "#F59E0B", // amber
      description: "The ultimate tier. Start your own WordPress web development agency.",
      features: [
        "Includes all contents of the Business Package.",
        "Domain Registrations(.com, .np, .org,).",
        "Web Hosting Provided(unlimited bandwith).",
        "Free SSL Certificates for your websites.",
        "C-panel Access for your websites.",
        "News Portal Website Development (WordPress).",
        "Website Development Trainings (WordPress) in Details.",
        "Content Writing Trainings on Website in Details.",
        "International Ads Monetization on Website.",
        "Professional Guidance & Mentorship.",
        "24/7 Technical Guidance, Community Support and Access.",
      ],
    }
  ] as Package[]
};
